'use client';

import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';

export default function TOSPage() {
  return (
    <div className="container mx-auto px-6 py-8 max-w-4xl">
      <Card>
        <CardHeader>
          <CardTitle className="text-3xl">Terms of Service</CardTitle>
          <p className="text-muted-foreground mt-2">
            Last Updated: {new Date().toLocaleDateString()}
          </p>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <h2 className="text-2xl font-bold mt-6 mb-4 text-foreground">
              Experimental Technology Notice
            </h2>
            <p className="text-foreground leading-7">
              Preceptra uses experimental AI technology to generate Standard Operating Procedures (SOPs),
              transcripts, and answer questions based on video content. By using this application, you acknowledge and agree to the following:
            </p>

            <h3 className="text-xl font-semibold mt-6 mb-3 text-foreground">
              1. AI-Generated Content
            </h3>
            <p className="text-foreground leading-7">
              All content generated by Preceptra, including but not limited to SOPs, transcripts, answers,
              and summaries, is produced by artificial intelligence and may contain errors, inaccuracies,
              or omissions.
            </p>

            <h3 className="text-xl font-semibold mt-6 mb-3 text-foreground">
              2. User Responsibility
            </h3>
            <div className="bg-amber-50 dark:bg-amber-950 border-l-4 border-amber-500 p-4 my-4">
              <p className="text-foreground leading-7 font-semibold">
                You are solely responsible for reviewing, verifying, and validating all AI-generated content.
              </p>
            </div>
            <p className="text-foreground leading-7">
              The final judgment and decision-making authority rests entirely with you, the user. Never rely solely
              on AI-generated content for critical decisions, safety procedures, or operational guidelines without
              thorough human review.
            </p>

            <h3 className="text-xl font-semibold mt-6 mb-3 text-foreground">
              3. No Liability
            </h3>
            <p className="text-foreground leading-7">
              We are not responsible for any consequences arising from the use of AI-generated content, including
              but not limited to:
            </p>
            <ul className="list-disc ml-6 space-y-2 text-foreground my-4">
              <li className="leading-7">Operational errors or failures</li>
              <li className="leading-7">Safety incidents or injuries</li>
              <li className="leading-7">Financial losses</li>
              <li className="leading-7">Incorrect or incomplete procedures</li>
              <li className="leading-7">Misinterpretation of video content</li>
              <li className="leading-7">Data inaccuracies or hallucinations</li>
              <li className="leading-7">Compliance violations</li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3 text-foreground">
              4. Verification Required
            </h3>
            <p className="text-foreground leading-7">
              Always verify AI-generated procedures with subject matter experts, compare with official documentation,
              and conduct appropriate testing before implementing any procedures in production environments.
            </p>
            <p className="text-foreground leading-7 mt-3">
              Recommended verification steps:
            </p>
            <ul className="list-disc ml-6 space-y-2 text-foreground my-4">
              <li className="leading-7">Review all AI-generated content with qualified personnel</li>
              <li className="leading-7">Cross-reference with official documentation and industry standards</li>
              <li className="leading-7">Conduct testing in controlled environments</li>
              <li className="leading-7">Obtain necessary approvals from management and compliance teams</li>
              <li className="leading-7">Document any deviations from AI-generated recommendations</li>
            </ul>

            <h3 className="text-xl font-semibold mt-6 mb-3 text-foreground">
              5. Data Privacy and Security
            </h3>
            <p className="text-foreground leading-7">
              By uploading videos and content to Preceptra, you confirm that you have the necessary rights
              and permissions to use such content. You are responsible for ensuring that uploaded content
              does not contain sensitive, confidential, or proprietary information that should not be processed
              by third-party AI systems.
            </p>

            <h3 className="text-xl font-semibold mt-6 mb-3 text-foreground">
              6. Alpha/Beta Software
            </h3>
            <p className="text-foreground leading-7">
              Preceptra is currently in alpha/beta testing. The software may contain bugs, errors, or
              unexpected behavior. Features may change, be removed, or function differently without notice.
              Service availability is not guaranteed.
            </p>

            <h3 className="text-xl font-semibold mt-6 mb-3 text-foreground">
              7. No Warranties
            </h3>
            <p className="text-foreground leading-7">
              The software is provided &quot;as is&quot; without warranty of any kind, express or implied,
              including but not limited to warranties of merchantability, fitness for a particular purpose,
              or non-infringement.
            </p>

            <h3 className="text-xl font-semibold mt-6 mb-3 text-foreground">
              8. Limitation of Liability
            </h3>
            <p className="text-foreground leading-7">
              In no event shall Preceptra, its creators, or affiliates be liable for any direct, indirect,
              incidental, special, consequential, or punitive damages arising out of or relating to your
              use of the service, even if advised of the possibility of such damages.
            </p>

            <h3 className="text-xl font-semibold mt-6 mb-3 text-foreground">
              9. Acceptance
            </h3>
            <p className="text-foreground leading-7">
              By using Preceptra, you acknowledge that you have read, understood, and agree to be bound by
              these Terms of Service. You confirm that you will review all AI-generated results and exercise
              final judgment in their use.
            </p>

            <h3 className="text-xl font-semibold mt-6 mb-3 text-foreground">
              10. Changes to Terms
            </h3>
            <p className="text-foreground leading-7">
              We reserve the right to modify these terms at any time. Continued use of the service after
              changes constitutes acceptance of the modified terms.
            </p>

            <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-6 mt-8">
              <h4 className="text-lg font-semibold text-foreground mb-2">
                Contact Information
              </h4>
              <p className="text-foreground leading-7">
                If you have questions about these Terms of Service, please contact us at:
              </p>
              <p className="text-foreground mt-2">
                <a
                  href="mailto:info@trymlink.com"
                  className="text-blue-600 dark:text-blue-400 hover:underline font-medium"
                >
                  info@trymlink.com
                </a>
              </p>
              <p className="text-foreground mt-1">
                <a
                  href="https://trymlink.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 dark:text-blue-400 hover:underline font-medium"
                >
                  trymlink.com
                </a>
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
